export const movieGenres = {
  action: 28,
  adventure: 12,
  animation: 16,
  comedy: 35,
  crime: 80,
  documentary: 99,
  drama: 18,
  family: 10751,
  fantasy: 14,
  history: 36,
  horror: 27,
  music: 10402,
  mystery: 9648,
  romance: 10749,
  thriller: 53,
  war: 10752,
  western: 37,
};

export const movieLanguages = {
  en: "English",
  ja: "Japanese",
  ko: "Korean",
  zh: "Chinese",
  fr: "French",
  es: "Spanish",
  de: "German",
  it: "Italian",
  ru: "Russian",
  pt: "Portuguese",
  hi: "Hindi",
  ar: "Arabic",
  bn: "Bengali",
  id: "Indonesian",
  tr: "Turkish",
  pl: "Polish",
  th: "Thai",
  nl: "Dutch",
  sv: "Swedish",
  da: "Danish",
  fi: "Finnish",
  no: "Norwegian",
  hu: "Hungarian",
  cs: "Czech",
  el: "Greek",
  he: "Hebrew",
  ro: "Romanian",
  sk: "Slovak",
  uk: "Ukrainian",
  vi: "Vietnamese",
};
